name: inherited_store
description: An inherited widget that holds data and rebuilds the widgets whom depend on the changed data.
version: 0.3.3
homepage: https://github.com/ali2236/inherited_store

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
